.dockerignore
.editorconfig
.gitignore
.tractusx
.vscode/settings.json
CODE_OF_CONDUCT.md
CONTRIBUTING.md
FILEHEADER.md
LICENSE
NOTICE.md
SECURITY.md

add general files to repository
To have contribution guidlines, as well as the code of conduct and license available
N/A

chore: add general files

---

.github/workflows/chart-test.yml
.github/workflows/dependencies.yml
.github/workflows/owasp-zap.yml
.github/workflows/unit.tests-formatting.yml
CONTRIBUTING.md
charts/ssi-credential-issuer/templates/cronjob-expiry-app.yaml
charts/ssi-credential-issuer/templates/cronjob-issuer-processes.yaml
charts/ssi-credential-issuer/values.yaml
consortia/environments/values-dev.yaml
consortia/environments/values-rc.yaml
scripts/check-dependencies.md

- chore(helm-test): fix image name and tag override at upgrade
- chore: fix owasp scan
- chore(helm-test and owasp): change set command
- chore: re-arrange values file
- chore(pre-checks): run only on changes to src/**
- docs(CONTRIBUTING.md): update to contribution details
- chore: fix db dependency secret name in cronjobs
- chore(dependencies-check): align file naming and docs
- chore: remove white space
#20 
#11

chore: fix helm chart, improve workflows and docs

---

.github/workflows/migrations-docker.yml
.github/workflows/processes-worker-docker.yml
.github/workflows/release.yml
.github/workflows/service-docker.yml
README.md

- chore: fix referencing of dockerfile and notices
- chore(release): add processesworker to workflow
https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/18

chore: fix image build

---

.github/workflows/credential-expiry-app-docker.yml
.github/workflows/migrations-docker.yml
.github/workflows/processes-worker-docker.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/service-docker.yml
charts/ssi-credential-issuer/README.md
charts/ssi-credential-issuer/values.yaml
docker/notice-credential-expiry-app.md
docker/notice-credential-issuer-migrations.md
docker/notice-credential-issuer-processes-worker.md

- chore: fix naming of docker images
- fix workflow trigger
- docs: update chart readme
follow up to https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/18

chore: fix naming of docker images and workflow trigger

---

.github/workflows/processes-worker-docker.yml
.github/workflows/trivy-dev.yml
.github/workflows/trivy.yml

chore(trivy): scan correct images
chore(processesworker): fix workflow trigger
follow up to https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/29

chore: scan correct images and fix workflow trigger

---

.github/workflows/chart-release.yaml
.github/workflows/chart-test.yml
.github/workflows/credential-expiry-app-docker.yml
.github/workflows/dependencies.yml
.github/workflows/kics.yml
.github/workflows/lint-pull-request.yml
.github/workflows/migrations-docker.yml
.github/workflows/processes-worker-docker.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/service-docker.yml
.github/workflows/sonarcloud.yml
.github/workflows/trivy-dev.yml
.github/workflows/trivy.yml
.github/workflows/unit.tests-formatting.yml

upgrade gh actions and change to pinned actions full length commit sha
https://github.com/eclipse-tractusx/portal/issues/225

chore(gh-actions): upgrade and change to pinned commit sha

---

.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/unit.tests-formatting.yml

- chore: fix release-candidate and pre-check workflow
- chore(release): don't run jobs unnecessarily
- chore(release-candidate): improve workflow

chore: fix and improve workflows

---

consortia/environments/values-beta.yaml
consortia/environments/values-dev.yaml
consortia/environments/values-int.yaml
consortia/environments/values-pen.yaml
consortia/environments/values-rc.yaml

fix credential expiry config overwrite for consortia environments

chore(consortia-envs): fix credential expiry config overwrite

---

consortia/environments/values-beta.yaml
consortia/environments/values-dev.yaml
consortia/environments/values-int.yaml
consortia/environments/values-pen.yaml
consortia/environments/values-rc.yaml
src/externalservices/Wallet.Service/Schemas/BPNCredential.schema.json
src/externalservices/Wallet.Service/Schemas/FRAMEWORKCredential.schema.json
src/externalservices/Wallet.Service/Schemas/MEMBERSHIPCredential.schema.json
tests/externalservices/Wallet.Service.Tests/BusinessLogic/WalletBusinessLogicTests.cs

Adjust schemas for validation
The schema of the json isn't as the schemas expected. therefor they have been adjusted
N/A
- [x ] I have checked that new and existing tests pass locally with my changes

fix(ssi): adjust schemas

---

charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
consortia/argocd-app-templates/appsetup-int.yaml
consortia/argocd-app-templates/appsetup-pen.yaml
consortia/argocd-app-templates/appsetup-stable.yaml
src/Directory.Build.props

Bump version for v1.0.0-rc.2
To have a new version for the release
https://github.com/eclipse-tractusx/portal/issues/264

build: bump version for v1.0.0-rc.2

---

charts/ssi-credential-issuer/templates/cronjob-issuer-processes.yaml
src/database/SsiCredentialIssuer.DbAccess/Models/OwnedVerifiedCredentialData.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/CompanySsiDetailsRepository.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/ICompanySsiDetailsRepository.cs
src/externalservices/Callback.Service/DependencyInjection/CallbackSettings.cs
src/externalservices/Callback.Service/DependencyInjection/ServiceCollectionExtensions.cs
src/externalservices/Wallet.Service/DependencyInjection/WalletSettings.cs
src/externalservices/Wallet.Service/Schemas/FRAMEWORKCredential.schema.json
src/externalservices/Wallet.Service/Schemas/MEMBERSHIPCredential.schema.json
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IIssuerBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/Controllers/IssuerController.cs
src/processes/CredentialProcess.Library/DependencyInjection/CredentialHandlerExtensions.cs
src/processes/CredentialProcess.Worker/DependencyInjection/CredentialProcessCollectionExtensions.cs
src/processes/Processes.Worker/Program.cs
tests/database/SsiCredentialIssuer.DbAccess.Tests/CompanySsiDetailsRepositoryTests.cs
tests/externalservices/Callback.Service.Tests/CallbackServiceTests.cs
tests/externalservices/Wallet.Service.Tests/BusinessLogic/WalletBusinessLogicTests.cs
tests/externalservices/Wallet.Service.Tests/Services/WalletServiceTests.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs

Set the correct base address for the callback service
To support the callback to the portal backend
Refs: #71

fix(callback): set the correct base address for the callback

---

src/database/SsiCredentialIssuer.Entities/Enums/VerifiedCredentialExternalTypeId.cs
src/database/SsiCredentialIssuer.Entities/Enums/VerifiedCredentialTypeId.cs
src/database/SsiCredentialIssuer.Migrations/Migrations/20240507092202_97-AddQualityCredential.Designer.cs
src/database/SsiCredentialIssuer.Migrations/Migrations/20240507092202_97-AddQualityCredential.cs
src/database/SsiCredentialIssuer.Migrations/Seeder/Data/use_cases.json
src/database/SsiCredentialIssuer.Migrations/Seeder/Data/verified_credential_external_type_detail_versions.json
src/database/SsiCredentialIssuer.Migrations/Seeder/Data/verified_credential_type_assigned_external_types.json
src/database/SsiCredentialIssuer.Migrations/Seeder/Data/verified_credential_type_assigned_kinds.json
src/database/SsiCredentialIssuer.Migrations/Seeder/Data/verified_credential_type_assigned_use_cases.json
tests/database/SsiCredentialIssuer.DbAccess.Tests/CompanySsiDetailsRepositoryTests.cs
tests/externalservices/Wallet.Service.Tests/Services/BasicAuthTokenServiceTests.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs
tests/processes/Processes.Worker.Library.Tests/ProcessExecutorTests.cs

Re add the framework quality credential 
The framework quality credential is needed
Refs: #107

fix(qualityCredential): re add quality credential

---

src/database/SsiCredentialIssuer.Migrations/Seeder/Data/verified_credential_external_type_detail_versions.consortia.json
src/database/SsiCredentialIssuer.Migrations/Seeder/Data/verified_credential_external_type_detail_versions.json
tests/database/SsiCredentialIssuer.DbAccess.Tests/CompanySsiDetailsRepositoryTests.cs

Adjust expiry data for credentials
The expiry of the credentials have been adjusted
Refs: #108

chore(expiry): adjust seeding

---

docs/architecture/Security_Assessment.md

Added security assessment documentation
The document is needed for the quality gate
N/A

docs: add security assessment documentation

---

charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
consortia/argocd-app-templates/appsetup-int.yaml
consortia/argocd-app-templates/appsetup-stable.yaml

finalize version-1.0.0 rc.4 by merge into main
https://github.com/eclipse-tractusx/portal/issues/308

build(1.0.0-rc.4): bump chart version and update docs

---

docs/architecture/Architecture Constraints.md
docs/architecture/Context and scope.md
docs/architecture/Requirements.md

Aarc42 enhancement with business context
Added additional information from product owner side
#119

docs: arc42 enhancement with business context

---

CHANGELOG.md
README.md
charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
charts/ssi-credential-issuer/values.yaml
consortia/argocd-app-templates/appsetup-beta.yaml
consortia/argocd-app-templates/appsetup-int.yaml
consortia/argocd-app-templates/appsetup-pen.yaml
consortia/argocd-app-templates/appsetup-stable.yaml
consortia/argocd-app-templates/appsetup-upgrade.yaml
docs/architecture/Architecture Constraints.md
docs/architecture/Context and scope.md
docs/architecture/Requirements.md
docs/technical-documentation/known-knowns/known-issues-and-limitations.md
src/Directory.Build.props
src/database/SsiCredentialIssuer.DbAccess/Models/CredentialDetailData.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/RevocationBusinessLogic.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/RevocationBusinessLogicTests.cs

finalize version-1.0.0 rc.6 by merge into main
https://github.com/eclipse-tractusx/portal/issues/328

build(1.0.0-rc.6): bump chart version and update docs

---

CHANGELOG.md
charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
consortia/argocd-app-templates/appsetup-beta.yaml
consortia/argocd-app-templates/appsetup-int.yaml
consortia/argocd-app-templates/appsetup-pen.yaml
consortia/argocd-app-templates/appsetup-stable.yaml
consortia/argocd-app-templates/appsetup-upgrade.yaml
consortia/environments/values-beta.yaml
consortia/environments/values-dev.yaml
consortia/environments/values-int.yaml
consortia/environments/values-pen.yaml
consortia/environments/values-rc.yaml
src/Directory.Build.props

finalize version-1.0.0 by merge into main
https://github.com/eclipse-tractusx/sig-release/issues/673

build(1.0.0): release version

---

.github/workflows/chart-test.yml
DEPENDENCIES

- add upgrade step to helm-test workflow
after first stable was released
https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/136

chore(helm-test): add upgrade step

---

.github/workflows/credential-expiry-app-docker.yml
.github/workflows/migrations-docker.yml
.github/workflows/processes-worker-docker.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/service-docker.yml
docker/Dockerfile-credential-expiry-app
docker/Dockerfile-credential-issuer-migrations
docker/Dockerfile-credential-issuer-processes-worker
docker/Dockerfile-credential-issuer-service

- change from emulation to cross-compile for building multi-platform images
- also, improve dockerfiles by removing unnecessary base stage and aligning environment variables
https://github.com/eclipse-tractusx/portal-backend/issues/802
https://docs.docker.com/build/building/multi-platform
https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support

fix(image-build): change from emulation to cross-compile

---

environments/helm-values/values-int.yaml

change to consolidation from
https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/172
update deployment config
https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/186

chore(1.1.0-rc.1): change structure in values.yaml of association env

---

DEPENDENCIES
charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
charts/ssi-credential-issuer/README.md.gotmpl
docs/technical-documentation/known-knowns/known-issues-and-limitations.md
docs/technical-documentation/operator-credential-creation/initial-credential-setup.md
environments/argocd-app-templates/appsetup-int.yaml
environments/consortia/argocd-app-templates/appsetup-int.yaml
src/Directory.Build.props
src/credentials/SsiCredentialIssuer.Expiry.App/SsiCredentialIssuer.Expiry.App.csproj
src/database/SsiCredentialIssuer.DbAccess/SsiCredentialIssuer.DbAccess.csproj
src/database/SsiCredentialIssuer.Entities/SsiCredentialIssuer.Entities.csproj
src/database/SsiCredentialIssuer.Migrations/SsiCredentialIssuer.Migrations.csproj
src/externalservices/Callback.Service/Callback.Service.csproj
src/externalservices/Portal.Service/Portal.Service.csproj
src/externalservices/Wallet.Service/Wallet.Service.csproj
src/issuer/SsiCredentialIssuer.Service/SsiCredentialIssuer.Service.csproj
src/processes/Processes.Worker.Library/Processes.Worker.Library.csproj
src/processes/Processes.Worker/Processes.Worker.csproj
tests/database/SsiCredentialIssuer.DbAccess.Tests/SsiCredentialIssuer.DbAccess.Tests.csproj
tests/externalservices/Wallet.Service.Tests/Wallet.Service.Tests.csproj

Merge the latest changes to the main branch
To have the latest changes available in the main branch
https://github.com/eclipse-tractusx/portal/issues/349

build(1.1.0): merge release into main

---

docs/database/db-view.md

adjusted the formatting and markup of the file for better readability.
no changes done in terms of content. 
Updated db-view.md for better readability 
n.a.

docs: Update db-view.md

---

src/database/SsiCredentialIssuer.Migrations/Seeder/Data/verified_credential_external_type_detail_versions.json

Updated the the template framework pdf link.
The framework pdf link was changed.
Na

fix: update the template framework pdf link

---

.tractusx
CHANGELOG.md
charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
docs/api/issuer-service.yaml
src/Directory.Build.props

Merge the latest release into main
To have the latest release available in main
N/A

build: merge release into main

---

.tractusx
CHANGELOG.md
charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
docs/api/issuer-service.yaml
environments/argocd-app-templates/appsetup-int.yaml
environments/argocd-app-templates/appsetup-stable.yaml
src/Directory.Build.props

Merge the latest release into main
To have the latest changes available in the main branch
https://github.com/eclipse-tractusx/portal/issues/502

build(1.3.0-rc.1): merge release into main

---

.tractusx
README.md
charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
charts/ssi-credential-issuer/README.md.gotmpl
docs/admin/known-issues-and-limitations.md
docs/api/issuer-service.yaml
environments/argocd-app-templates/appsetup-int.yaml
environments/argocd-app-templates/appsetup-stable.yaml
environments/helm-values/values-int.yaml
src/Directory.Build.props

prepare release finalisation of of version 1.3.0
https://github.com/eclipse-tractusx/sig-release/issues/1132

build(1.3.0): bump version and update docs

---

.tractusx
CHANGELOG.md
charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
docs/api/issuer-service.yaml
environments/argocd-app-templates/appsetup-int.yaml
environments/argocd-app-templates/appsetup-stable.yaml
src/Directory.Build.props

merge the release into the main branch
to have the latest release changes available in main
[#541](https://github.com/eclipse-tractusx/portal/issues/541)

build(v1.4.0-rc.1): merge release into main

---

.gitignore
DEPENDENCIES
docs/api/issuer-service.yaml
src/credentials/SsiCredentialIssuer.Expiry.App/SsiCredentialIssuer.Expiry.App.csproj
src/database/SsiCredentialIssuer.DbAccess/SsiCredentialIssuer.DbAccess.csproj
src/database/SsiCredentialIssuer.Entities/SsiCredentialIssuer.Entities.csproj
src/database/SsiCredentialIssuer.Migrations/SsiCredentialIssuer.Migrations.csproj
src/externalservices/Callback.Service/Callback.Service.csproj
src/externalservices/Portal.Service/Portal.Service.csproj
src/externalservices/Wallet.Service/Wallet.Service.csproj
src/issuer/SsiCredentialIssuer.Service/SsiCredentialIssuer.Service.csproj
src/processes/CredentialProcess.Library/CredentialProcess.Library.csproj
src/processes/CredentialProcess.Worker/CredentialProcess.Worker.csproj
src/processes/Processes.ProcessIdentity/Processes.ProcessIdentity.csproj
src/processes/Processes.Worker/Processes.Worker.csproj
tests/Tests.Shared/Tests.Shared.csproj
tests/credentials/SsiCredentialIssuer.Expiry.App.Tests/SsiCredentialIssuer.Expiry.App.Tests.csproj
tests/database/SsiCredentialIssuer.DbAccess.Tests/SsiCredentialIssuer.DbAccess.Tests.csproj
tests/externalservices/Callback.Service.Tests/Callback.Service.Tests.csproj
tests/externalservices/Portal.Service.Tests/Portal.Service.Tests.csproj
tests/externalservices/Wallet.Service.Tests/Wallet.Service.Tests.csproj
tests/issuer/SsiCredentialIssuer.Service.Tests/SsiCredentialIssuer.Service.Tests.csproj
tests/processes/CredentialProcess.Library.Tests/CredentialProcess.Library.Tests.csproj
tests/processes/CredentialProcess.Worker.Tests/CredentialProcess.Worker.Tests.csproj
tests/processes/Processes.ProcessIdentity.Tests/Processes.ProcessIdentity.Tests.csproj

update the dependencies
to have the latest version of the external packages available
Refs: #281

chore: update dependencies

---

.tractusx
CHANGELOG.md
charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
docs/api/issuer-service.yaml
environments/argocd-app-templates/appsetup-int.yaml
environments/argocd-app-templates/appsetup-stable.yaml
src/Directory.Build.props

merge the release into the main branch
to have the latest release changes available in main
[#541](https://github.com/eclipse-tractusx/portal/issues/541)

build(v1.4.0-rc.2): merge release into main 

---

.tractusx
CHANGELOG.md
charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
docs/api/issuer-service.yaml
environments/argocd-app-templates/appsetup-int.yaml
environments/argocd-app-templates/appsetup-stable.yaml
src/Directory.Build.props

Merge the latest release into main
to have the latest changes in main
n/A

build(v1.4.1-rc.1): merge release into main
