eclipse-tractusx/ssi-credential-issuer

.github/pull_request_template.md
.github/workflows/chart-release.yaml
.github/workflows/chart-test.yml
.github/workflows/codeql.yml
.github/workflows/dependencies.yml
.github/workflows/kics.yml
.github/workflows/lint-pull-request.yml
.github/workflows/migrations-docker.yml
.github/workflows/owasp-zap.yml
.github/workflows/release-please.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/service-docker.yml
.github/workflows/sonarcloud.yml
.github/workflows/trivy-dev.yml
.github/workflows/trivy.yml
.github/workflows/unit.tests-formatting.yml
docs/technical-documentation/dev-process/Dev-flow_deploy-dev-env.md
docs/technical-documentation/dev-process/Dev-flow_git-diagram.md
docs/technical-documentation/dev-process/How to contribute.md
scripts/add_notice_footer.sh
scripts/check-dependencies.md
scripts/license.sh

add workflows to check the quality of the code
To add quality checks to the repo
#2

chore: add workflows

---

.github/workflows/credential-expiry-app-docker.yml
.github/workflows/migrations-docker.yml
.github/workflows/processes-worker-docker.yml
.github/workflows/service-docker.yml
docker/Dockerfile-credential-expiry-app

- fix dockerfile for SsiCredentialIssuer.Expiry.App
- fix reference to dockerfile
- chore: rename image build workflows
#18
#20

fix(build): enable build of docker images

---

consortia/environments/values-beta.yaml
consortia/environments/values-dev.yaml
consortia/environments/values-int.yaml
consortia/environments/values-pen.yaml
consortia/environments/values-rc.yaml

Added paths to environment specific configurations of clientIds and secrets
To have environment specific values for the clientIds and secrets
N/A

feat(helm): add paths for environment values

---

consortia/environments/values-pen.yaml
consortia/environments/values-rc.yaml
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs

Adjusting the routing url, to remove the -backend of the subdomain
The SSI Credential Issuer will not have a frontend, therefore the subdomain prefix -backend isn't needed.
N/A

fix: adjust the hosting url for rc and pen

---

DEPENDENCIES
src/externalservices/Wallet.Service/Schemas/BPNCredential.schema.json
tests/externalservices/Wallet.Service.Tests/BusinessLogic/WalletBusinessLogicTests.cs

fixed typo in the bpn schema
The bpn schema has a typo in holderIdentifier
N/A

fix: adjust bpn schema

---

consortia/environments/values-beta.yaml
consortia/environments/values-dev.yaml
consortia/environments/values-int.yaml
consortia/environments/values-pen.yaml
consortia/environments/values-rc.yaml
src/database/SsiCredentialIssuer.Migrations/Seeder/BatchUpdateSeeder.cs
src/database/SsiCredentialIssuer.Migrations/Seeder/Data/verified_credential_external_type_detail_versions.consortia.json

* add consortia to the seeding paths to seed consortia related data
The seeding didn't seed consortia specific use cases, therefor some of them were missing
Refs: #94 , #45

fix(seeding): set consortia to seeding paths

---

src/externalservices/Portal.Service/Services/PortalService.cs

adjust notification creation url
the call of the notification creation endpoint fails with a 404
N/A

fix(notification): adjust notification creation url

---

src/externalservices/Portal.Service/Services/PortalService.cs
tests/externalservices/Portal.Service.Tests/PortalServiceTests.cs

Adjust enum serialisation for notification creation
To send a correct request to the portal
N/A

fix(notification): adjust enum serialization

---

src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs

Remove duplicate credential from credential name of framework credentials
The duplicate Credential is resulting in an error for the communication of the edc.
Refs: TEST-1997

fix(credential): remove duplicate credential

---

src/database/SsiCredentialIssuer.DbAccess/Models/SsiApprovalData.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/CompanySsiDetailsRepository.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/ICompanySsiDetailsRepository.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs

Adjust the mail and notification creation to create them for the requesting user instead of the calling user.
Since the calling user is the operator, the requesting user is currently not informed about the approval / rejection of the credentials.
Refs: https://github.com/eclipse-tractusx/portal-backend/issues/712
[713](https://github.com/eclipse-tractusx/portal-backend/pull/713)

fix(approval): send mail and notification to requester

---

src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/Controllers/RevocationController.cs

Fix the framework credential check for pending credentials
The check currently is made with the bpn of the identity instead of the submitted holder bpn
N/A

fix(framework): adjust framework credential creation

---

src/database/SsiCredentialIssuer.Entities/Enums/VerifiedCredentialExternalTypeId.cs
src/issuer/SsiCredentialIssuer.Service/Controllers/RevocationController.cs

Instead of sending the DemandCapacityCredential the correct value PurisCredential is send.
Currently the wrong value is send to create the PurisCredential
Refs: #147

fix(credential): adjust puris credential naming

---

src/database/SsiCredentialIssuer.DbAccess/Models/OwnedVerifiedCredentialData.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/CompanySsiDetailsRepository.cs

Added the credential detail id to the response of the owned-credential endpoint
To revoke the credentials the id is needed, since the endpoint does not return the id it is added with this pr.
N/A

fix(ownedCredential): add credential id to response

---

src/database/SsiCredentialIssuer.DbAccess/Models/CompanySsiApprovalType.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/CompanySsiDetailsRepository.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/CredentialRepository.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/ICompanySsiDetailsRepository.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/ICredentialRepository.cs
src/database/SsiCredentialIssuer.Migrations/Seeder/BatchInsertSeeder.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/CredentialBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IIssuerBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/Controllers/CredentialController.cs
src/issuer/SsiCredentialIssuer.Service/Controllers/IssuerController.cs
src/issuer/SsiCredentialIssuer.Service/ErrorHandling/CredentialErrorMessageContainer.cs
src/issuer/SsiCredentialIssuer.Service/Identity/MandatoryIdentityClaimHandler.cs
tests/database/SsiCredentialIssuer.DbAccess.Tests/CompanySsiDetailsRepositoryTests.cs
tests/database/SsiCredentialIssuer.DbAccess.Tests/CredentialRepositoryTests.cs
tests/database/SsiCredentialIssuer.DbAccess.Tests/Seeder/Data/company_ssi_detail_assigned_documents.test.json
tests/database/SsiCredentialIssuer.DbAccess.Tests/Seeder/Data/company_ssi_process_datas.test.json
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/CredentialBusinessLogicTests.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/Controllers/IssuerControllerTests.cs

* add optional filter for approval type to endpoitn GET /api/issuer
* add Get document endpoint
To give the customer the possibility to filter for credentials that need approval and won't be automatically approved.
Refs: #111 #27

feat(issuer): add filter to /api/issuer

---

charts/ssi-credential-issuer/values.yaml
src/database/SsiCredentialIssuer.DbAccess/Models/CredentialDetailData.cs

Adjust the api path to handle the requests to api/revocation and api/credential as well.
... and improve formatting
The ingress blocks requests to the api/recovation and api/credential endpoints
N/A

fix(ingress): adjust api path

---

src/issuer/SsiCredentialIssuer.Service/BusinessLogic/RevocationBusinessLogic.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/RevocationBusinessLogicTests.cs

Save the database changes after the revocation of the credential
To have the new and correct status in the database
N/A

fix(revocation): save database changes afert revocation

---

README.md
docs/technical-documentation/known-knowns/known-issues-and-limitations.md

Added a Known Issues and Limitations section to the readme
To display the known knowns to the user
N/A

docs: add known knowns section to readme

---

consortia/environments/values-beta.yaml
consortia/environments/values-dev.yaml
consortia/environments/values-int.yaml
consortia/environments/values-pen.yaml
consortia/environments/values-rc.yaml

Fix the ingress configuration for each environment
Requests to /api/revocation lead to an 404 due to a wrong ingress configuration
N/A

chore(consortia): fix ingress in environment specific config

---

.github/workflows/chart-test.yml
.github/workflows/owasp-zap.yml
charts/ssi-credential-issuer/README.md
charts/ssi-credential-issuer/templates/cronjob-issuer-processes.yaml
charts/ssi-credential-issuer/templates/deployment-issuer-service.yaml
charts/ssi-credential-issuer/templates/job-issuer-migrations.yaml
charts/ssi-credential-issuer/templates/secret.yaml
charts/ssi-credential-issuer/values.yaml
consortia/argocd-app-templates/appsetup-stable.yaml
consortia/environments/values-beta.yaml
consortia/environments/values-dev.yaml
consortia/environments/values-int.yaml
consortia/environments/values-pen.yaml
consortia/environments/values-rc.yaml

rename issuer node to service and issuermigrations to migrations
improve helm chart

feat(helm): consolidate structure in values.yaml 

---

src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs

Set the expiry to max 1 year for framework credentials if the expiry for the detail version is longer than 1 year.
To have the credentials validity max one year in the future
N/A

fix(expiry): set expiry to max 1 year

---

src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs

Adjust the document names for presentation documents to display the credential name instead of schema.json
To have a better overview of the content of the document
Refs: #166

fix(document): adjust document name for presentation docs

---

docs/database/db-view.md

Added documentation for the database
To give a more in detail description of the tables and their content
Refs: #167

docs: add db documentation

---

.github/workflows/sonarcloud.yml

fix actions/cache in sonarcloud: change commit sha
Error: Unable to resolve action `actions/cache@c45773b623bea8c8e75f6c82b208c3cf94ea4f9`, unable to find version `c45773b623bea8c8e75f6c82b208c3cf94ea4f9`
Inroduced with https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/177

ci: fix actions/cache in sonarcloud

---

src/credentials/SsiCredentialIssuer.Expiry.App/Program.cs
src/credentials/SsiCredentialIssuer.Expiry.App/SsiCredentialIssuer.Expiry.App.csproj
src/database/SsiCredentialIssuer.DbAccess/SsiCredentialIssuer.DbAccess.csproj
src/database/SsiCredentialIssuer.Entities/SsiCredentialIssuer.Entities.csproj
src/database/SsiCredentialIssuer.Migrations/Program.cs
src/database/SsiCredentialIssuer.Migrations/SsiCredentialIssuer.Migrations.csproj
src/externalservices/Callback.Service/Callback.Service.csproj
src/externalservices/Portal.Service/Portal.Service.csproj
src/externalservices/Wallet.Service/BusinessLogic/WalletBusinessLogic.cs
src/externalservices/Wallet.Service/Wallet.Service.csproj
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerSettings.cs
src/issuer/SsiCredentialIssuer.Service/Program.cs
src/issuer/SsiCredentialIssuer.Service/SsiCredentialIssuer.Service.csproj
src/processes/Processes.Worker.Library/Processes.Worker.Library.csproj
src/processes/Processes.Worker/Processes.Worker.csproj
src/processes/Processes.Worker/Program.cs
tests/database/SsiCredentialIssuer.DbAccess.Tests/SsiCredentialIssuer.DbAccess.Tests.csproj
tests/externalservices/Wallet.Service.Tests/Wallet.Service.Tests.csproj
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs

Exception-handling was added to the CryptoHelper to properly map the System-exceptions that are thrown by the Aes-classes to Configuration resp. ConflictExceptions
To handle the exceptions thrown by the cryptoHandler to handle the failing process steps correctly
N/A

fix: adjust exceptionhandling for encryption

---

src/issuer/SsiCredentialIssuer.Service/Controllers/IssuerController.cs

Changed the object type CredentialDetailData to OwnedVerifiedCredentialData in the response of the Endpoint GET /api/issuer/owned-credentials.
The current OpenAI documentation for the endpoint GET /api/issuer/owned-credentials displays an incorrect response body
N/A

fix: Added the correct type for owned-credentials method

---

src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs

The expiry date was added during the BPNL and Membership creation
There is a bug within the company_ssi_details table where BPNL (Business Partner Number Legal) and Membership credentials are being issued without an expiry date
N/A

fix: Implement Expiry Date for BPNL and Membership

---

charts/ssi-credential-issuer/templates/cronjob-expiry-app.yaml
src/credentials/SsiCredentialIssuer.Expiry.App/appsettings.json

Added environment value for PortalSettings in `charts/ssi-credential-issuer/templates/cronjob-expiry-app.yaml` 
fixes  #195 
closes #195 
To run this project PortalSettings are required
[Issue #195](https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/195)

fix(cronjob expiry): added the missing environment value for portal

---

charts/ssi-credential-issuer/templates/cronjob-expiry-app.yaml
src/credentials/SsiCredentialIssuer.Expiry.App/ExpiryCheckService.cs
src/credentials/SsiCredentialIssuer.Expiry.App/appsettings.json
src/database/SsiCredentialIssuer.DbAccess/Repositories/CompanySsiDetailsRepository.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/ICompanySsiDetailsRepository.cs
src/database/SsiCredentialIssuer.DbAccess/SsiCredentialIssuer.DbAccess.csproj
tests/credentials/SsiCredentialIssuer.Expiry.App.Tests/ExpiryCheckServiceTests.cs
tests/database/SsiCredentialIssuer.DbAccess.Tests/CompanySsiDetailsRepositoryTests.cs

Set the bpn, issuerBpn and creatorUser to default values instead of null to support the auditing when deleting a companySsiDetail
The auditing was failing due to the bpn being null when deleting the companySsiDetail in the expiry app
Refs: #195

fix(expiry): adjust removal of companySsiDetails

---

src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs

adjusting the approval mail to include the bpn as company identifier
Since we don't have the company name available in the database of the ssi credential issuer we take the bpn, which is the only available information and set that as a identifier for the company in the approval mailing
Refs: #215

fix: set companyName for credentialApproval

---

src/credentials/SsiCredentialIssuer.Expiry.App/SsiCredentialIssuer.Expiry.App.csproj
src/database/SsiCredentialIssuer.DbAccess/SsiCredentialIssuer.DbAccess.csproj
src/database/SsiCredentialIssuer.Entities/SsiCredentialIssuer.Entities.csproj
src/database/SsiCredentialIssuer.Migrations/SsiCredentialIssuer.Migrations.csproj
src/issuer/SsiCredentialIssuer.Service/SsiCredentialIssuer.Service.csproj
tests/database/SsiCredentialIssuer.DbAccess.Tests/SsiCredentialIssuer.DbAccess.Tests.csproj
tests/externalservices/Callback.Service.Tests/Callback.Service.Tests.csproj
tests/externalservices/Portal.Service.Tests/Portal.Service.Tests.csproj
tests/externalservices/Wallet.Service.Tests/Wallet.Service.Tests.csproj
tests/issuer/SsiCredentialIssuer.Service.Tests/SsiCredentialIssuer.Service.Tests.csproj

increase efcore version to latest 8.0.7
efcore 8.0.3 has transitive dependency System.Text.Json 8.0.0 which has a security-vulerability that is clasified as high. Upgrade to efcore 8.0.7 implicitly upgrades this dependency to System.Text.Json 8.0.4 which resolves the vulnerability.
https://github.com/eclipse-tractusx/portal/issues/369

chore(dependencies): bump efcore to 8.0.7

---

charts/ssi-credential-issuer/README.md
charts/ssi-credential-issuer/README.md.gotmpl
docs/technical-documentation/operator-credential-creation/initial-credential-setup.md
docs/technical-documentation/operator-credential-creation/intial-credential-setup.md

Adding documentation for the initial credential creation for the operator
to give an overview of the initial credential creation process
Refs: #206

docs: add documentation for initial credential creation

---

src/database/SsiCredentialIssuer.DbAccess/Repositories/CredentialRepository.cs
tests/database/SsiCredentialIssuer.DbAccess.Tests/CredentialRepositoryTests.cs

Adjust the validation of endpoint GET: api/credential/documents/{documentId} to allow the issuer to display document of the requester.
The issuer is not able to display the requested credential documents.
Refs: #225

fix(document): adjust validation to allow the issuer to display documents of credentials

---

src/database/SsiCredentialIssuer.DbAccess/Models/OwnedVerifiedCredentialData.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/CompanySsiDetailsRepository.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs

We need to enhance the API response body by including a version attribute for API Path: GET /api/issuer/owned-credentials. 
For better traceability and version control.

feat(ssi): enhanced the owned-credentials endpoint

---

src/database/SsiCredentialIssuer.Migrations/Migrations/20240923070946_2.0.0-alpha.1.Designer.cs
src/database/SsiCredentialIssuer.Migrations/Migrations/20240923070946_2.0.0-alpha.1.cs

Merge all migrations since the last release into one
To only have one migration for the release
N/A

build(migrations): aggregate migrations

---

src/externalservices/Portal.Service/Models/NotificationRequest.cs
src/externalservices/Portal.Service/Services/IPortalService.cs
src/externalservices/Portal.Service/Services/PortalService.cs
tests/externalservices/Portal.Service.Tests/PortalServiceTests.cs

Adjust the request parameter to create notifications
The portal backend changed the request structure to create notifications
Refs: https://github.com/eclipse-tractusx/portal-backend/issues/812
https://github.com/eclipse-tractusx/portal-backend/pull/906
https://github.com/eclipse-tractusx/portal-iam/pull/169

feat(notification): adjust notification request parameter

---

src/externalservices/Wallet.Service/Models/CreateCredentialResponse.cs
src/externalservices/Wallet.Service/Services/WalletService.cs
tests/externalservices/Wallet.Service.Tests/Services/WalletServiceTests.cs

Adjusting the credential request structure
The current structure is not matching the expected structure
Introduced in 1.2.0-alpha.1, no stable version affected
Refs: #265

fix: adjust create credential request structure

---

src/database/SsiCredentialIssuer.Migrations/Migrations/20240923070946_1.2.0-alpha.1.Designer.cs
src/database/SsiCredentialIssuer.Migrations/Migrations/20240923070946_1.2.0-alpha.1.cs
src/database/SsiCredentialIssuer.Migrations/Migrations/20241010142309_1.2.0-alpha.2.Designer.cs
src/database/SsiCredentialIssuer.Migrations/Migrations/20241010142309_1.2.0-alpha.2.cs

rename migrations due to release of new version and one wrongly named 2.0.0-alpha.1 in course of https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/257
https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/271
https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/272

chore: rename migrations

---

src/database/SsiCredentialIssuer.DbAccess/Repositories/CredentialRepository.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/ICredentialRepository.cs
src/externalservices/Wallet.Service/BusinessLogic/IWalletBusinessLogic.cs
src/processes/CredentialProcess.Library/Creation/CredentialCreationProcessHandler.cs
tests/database/SsiCredentialIssuer.DbAccess.Tests/CredentialRepositoryTests.cs
tests/processes/CredentialProcess.Library.Tests/CredentialCreationProcessHandlerTests.cs

* check if the holder equals the issuer, if so skip the import credential for holder step
Currently the process step fails because the credential is already in the wallet
Refs: #250

feat: skip credential import if holder equals issuer

---

src/database/SsiCredentialIssuer.Migrations/Migrations/20241021072243_1.2.0-rc.1.Designer.cs
src/database/SsiCredentialIssuer.Migrations/Migrations/20241021072243_1.2.0-rc.1.cs

Rename the migration for alpha.2 to rc.1
The release is now feature complete thus no new migration will be created
Refs: #272

build: rename migrations for rc.1

---

src/externalservices/Wallet.Service/BusinessLogic/WalletBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
tests/externalservices/Wallet.Service.Tests/BusinessLogic/WalletBusinessLogicTests.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs

The credential is set to active only after it was created in the wallet
To have the correct state when the credential isn't created yet
Refs: #285

fix: set credential to active only after credential exists

---

docs/technical-documentation/operator-credential-creation/initial-credential-setup.md

Adjusted the documentation for the initial credential setup
To give an overview that the process is handled automatically
Refs: #250

docs: adjust documentation for credential seeding

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md

Fix the "How to Contribute" link.
The existing link is broken.
[Issue #483](https://github.com/eclipse-tractusx/portal/issues/483) 

docs: fix how to contribute link

---

.github/workflows/trivy-main.yml
.github/workflows/trivy.yml
.tractusx
CHANGELOG.md
charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/README.md
docs/admin/known-issues-and-limitations.md
docs/api/issuer-service.yaml
src/Directory.Build.props

merge latest changes into main
https://github.com/eclipse-tractusx/portal/issues/482

build(1.2.0): merge latest changes into main

---

charts/ssi-credential-issuer/templates/deployment-issuer-service.yaml
charts/ssi-credential-issuer/values.yaml
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerSettings.cs
src/issuer/SsiCredentialIssuer.Service/appsettings.json
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs

The statuslist type used for the credentials is now configureable
Since the currently used type for the status list (Statuslist2021) was hardcoded the type used in the credentials for the status list is now configureable to be able to use the BitstringStatusList
Refs: #299

feat: make statuslist type configureable

---

docs/api/issuer-service.yaml
src/database/SsiCredentialIssuer.DbAccess/Models/CredentialDetailData.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/CompanySsiDetailsRepository.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/ICompanySsiDetailsRepository.cs
src/database/SsiCredentialIssuer.DbAccess/SsiCredentialIssuer.DbAccess.csproj
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
tests/database/SsiCredentialIssuer.DbAccess.Tests/CompanySsiDetailsRepositoryTests.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs

add information about the process and process steps to GET: /api/issuer
To have the possibility to retrigger process steps
Refs: #300

feat: add process and process step status to GET /api/issuer endpoint

---

docs/api/issuer-service.yaml
src/database/SsiCredentialIssuer.DbAccess/Models/StatusType.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/CompanySsiDetailsRepository.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/ICompanySsiDetailsRepository.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IIssuerBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/BusinessLogic/IssuerBusinessLogic.cs
src/issuer/SsiCredentialIssuer.Service/Controllers/IssuerController.cs
tests/database/SsiCredentialIssuer.DbAccess.Tests/CompanySsiDetailsRepositoryTests.cs
tests/issuer/SsiCredentialIssuer.Service.Tests/BusinessLogic/IssuerBusinessLogicTests.cs

The purpose of this feature is to enhance the functionality of the existing GET /api/issuer/useCaseParticipation endpoint in the Issuer Component. The enhancement involves the ability to filter the returned list of use case participations by the status of the credentials (Active, Expired, or All).
Instead of always returning all use case credentials it gives the customer the power of retrieving it by status.
Issue
NA

feat: enhance use case participant get credential endpoint by supporting filters

---

src/credentials/SsiCredentialIssuer.Expiry.App/Program.cs
src/database/SsiCredentialIssuer.DbAccess/IssuerRepositoriesStartupServiceExtensions.cs
src/processes/Processes.ProcessIdentity/ProcessIdentityDataDetermination.cs
src/processes/Processes.ProcessIdentity/Processes.ProcessIdentity.csproj
src/processes/Processes.Worker/Processes.Worker.csproj
src/processes/Processes.Worker/Program.cs

Add missing registrations for process worker
The process worker doesn't start due to missing registrations
N/A

fix(processWorker): add missing registrations

---

src/credentials/SsiCredentialIssuer.Expiry.App/SsiCredentialIssuer.Expiry.App.csproj
src/database/SsiCredentialIssuer.DbAccess/SsiCredentialIssuer.DbAccess.csproj
src/database/SsiCredentialIssuer.Entities/SsiCredentialIssuer.Entities.csproj
src/database/SsiCredentialIssuer.Migrations/SsiCredentialIssuer.Migrations.csproj
src/externalservices/Callback.Service/Callback.Service.csproj
src/externalservices/Portal.Service/Portal.Service.csproj
src/externalservices/Wallet.Service/Wallet.Service.csproj
src/issuer/SsiCredentialIssuer.Service/Program.cs
src/issuer/SsiCredentialIssuer.Service/SsiCredentialIssuer.Service.csproj
src/processes/CredentialProcess.Library/CredentialProcess.Library.csproj
src/processes/CredentialProcess.Worker/CredentialProcess.Worker.csproj
src/processes/Processes.ProcessIdentity/Processes.ProcessIdentity.csproj
src/processes/Processes.Worker/Processes.Worker.csproj
tests/externalservices/Wallet.Service.Tests/Wallet.Service.Tests.csproj

fixing the current error handling
after the net 9 upgrade the general error handling was broken and always returned a 500
N/A

fix(errorHandling): adjust general error handler

---

environments/helm-values/values-int.yaml

Adjust int environment configuration
The creation of credentials was failing due to a wrongly configured statuslist
Refs: #343

fix(envs): adjust statusList url for int

---

src/database/SsiCredentialIssuer.Migrations/Seeder/Data/verified_credential_type_assigned_external_types.json

Description
Added two missing ids(BUSINESS_PARTNER_NUMBER and FRAMEWORK_AGREEMENT) into assigned external credential type table. 
Why
The Expiry App  service was failing due to missing ids which were not mapped into the verified_credential_type_assigned_external_types table. This was leading to an exception during the iteration of the credentials. 
N/a

fix: added missing ids to verified credential external types table

---

.github/workflows/dependencies.yml

- fix dotnet list command: does work with dotnet 9.0.104 but not with 9.0.202 (currently latest), we switch this pipeline to 9.0.104 as a workaround https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/359
- restrict workflow to relevant paths
- check always for the restricted dependencies regardless if file was changed
#359

chore: fix and improve dependencies check

---

charts/ssi-credential-issuer/Chart.yaml
charts/ssi-credential-issuer/templates/cronjob-expiry-app.yaml
charts/ssi-credential-issuer/templates/cronjob-issuer-processes.yaml

For the imagePullSecrets in the cronjob type template, the indentation needs to be two more spaces due to the fact that it has "one more father" than the Deployments or Jobs templates.

fix: change image pull secret indentation for jobs

---

src/credentials/SsiCredentialIssuer.Expiry.App/ExpiryCheckService.cs
src/database/SsiCredentialIssuer.DbAccess/Models/CredentialExpiryData.cs
src/database/SsiCredentialIssuer.DbAccess/Repositories/CompanySsiDetailsRepository.cs
tests/credentials/SsiCredentialIssuer.Expiry.App.Tests/ExpiryCheckServiceTests.cs

Enhanced the notification message for expired credentials
The current expired credential notification payload does not include enough usable information to specify which exact credential has expired
[Link to Github issue.](https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/353)

feat: Enhanced the notification message when the credential is expired
